export { render } from './vtree/diff'
export { handleActions } from './vtree/handleActions'
export { applyPatch } from './vdom/patch'
export { patchOp } from './vdom/patch-op'
export { handleThunk } from './vnode/handle-thunk'
export { isVirtualNode as isVNode } from './vnode/is-vnode'
export { isThunk } from './vnode/is-thunk'
export { isWidget } from './vnode/is-widget'
export { isHook } from './vnode/is-vhook'
export { VirtualPatch as VPatch } from './vnode/vpatch'
export { VirtualNode as VNode } from './vnode/vnode'
export { createElement } from './vdom/create-element'
export { createDomTree } from './vdom/create-dom-tree'